-- 执行剩余 DDL（hr_salary_grade 已创建成功，此脚本从 hr_employee_grade_log 开始）

CREATE TABLE IF NOT EXISTS `hr_employee_grade_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL DEFAULT 0,
  `employee_id` BIGINT NOT NULL,
  `employee_name` VARCHAR(64) NULL,
  `from_grade_code` VARCHAR(32) NULL,
  `to_grade_code` VARCHAR(32) NOT NULL,
  `change_type` TINYINT NOT NULL DEFAULT 1,
  `change_reason` VARCHAR(200) NULL,
  `flow_instance_id` BIGINT NULL,
  `effective_date` DATE NOT NULL,
  `basic_salary_before` DECIMAL(12,2) NULL,
  `basic_salary_after` DECIMAL(12,2) NULL,
  `create_by` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_employee` (`employee_id`, `create_time`),
  KEY `idx_company` (`company_id`),
  KEY `idx_flow_instance` (`flow_instance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='薪酬级别变更流水表';

CREATE TABLE IF NOT EXISTS `hr_salary_rule` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL DEFAULT 0,
  `rule_name` VARCHAR(128) NOT NULL,
  `bind_type` TINYINT NOT NULL DEFAULT 1,
  `post_id` BIGINT NULL,
  `grade_code` VARCHAR(32) NULL,
  `basic_salary` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `performance_base` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `position_allowance` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `other_allowance` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `fixed_month_bonus` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `social_security_rate` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `housing_fund_rate` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `remark` VARCHAR(500) NULL,
  `flow_instance_id` BIGINT NULL,
  `apply_status` TINYINT NOT NULL DEFAULT 1,
  `status` TINYINT NOT NULL DEFAULT 1,
  `create_by` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT NULL,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_delete` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_company_status` (`company_id`, `status`, `is_delete`),
  KEY `idx_post` (`post_id`, `is_delete`),
  KEY `idx_grade` (`grade_code`, `is_delete`),
  KEY `idx_flow_instance` (`flow_instance_id`),
  KEY `idx_apply_status` (`company_id`, `apply_status`, `is_delete`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='薪资规则模板表';

CREATE TABLE IF NOT EXISTS `hr_salary_batch_adjust` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL DEFAULT 0,
  `adjust_name` VARCHAR(128) NOT NULL,
  `adjust_mode` TINYINT NOT NULL DEFAULT 1,
  `adjust_value` DECIMAL(12,4) NOT NULL DEFAULT 0.00,
  `target_grade_code` VARCHAR(32) NULL,
  `effective_date` DATE NOT NULL,
  `total_count` INT NOT NULL DEFAULT 0,
  `success_count` INT NOT NULL DEFAULT 0,
  `fail_count` INT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 0,
  `flow_instance_id` BIGINT NULL,
  `remark` VARCHAR(500) NULL,
  `create_by` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT NULL,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_delete` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_company_status` (`company_id`, `status`, `is_delete`),
  KEY `idx_flow_instance` (`flow_instance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='批量调薪任务表';

CREATE TABLE IF NOT EXISTS `hr_salary_batch_adjust_item` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `batch_id` BIGINT NOT NULL,
  `employee_id` BIGINT NOT NULL,
  `employee_name` VARCHAR(64) NULL,
  `stall_id` BIGINT NULL,
  `basic_salary_before` DECIMAL(12,2) NULL,
  `basic_salary_after` DECIMAL(12,2) NULL,
  `grade_code_before` VARCHAR(32) NULL,
  `grade_code_after` VARCHAR(32) NULL,
  `adjust_value` DECIMAL(12,4) NOT NULL DEFAULT 0.00,
  `adjust_mode` TINYINT NOT NULL DEFAULT 1,
  `result_status` TINYINT NOT NULL DEFAULT 0,
  `result_msg` VARCHAR(500) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_batch` (`batch_id`),
  KEY `idx_employee` (`employee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='批量调薪明细表';

CREATE TABLE IF NOT EXISTS `hr_year_bonus` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` BIGINT NOT NULL DEFAULT 0,
  `employee_id` BIGINT NOT NULL,
  `employee_name` VARCHAR(64) NULL,
  `bonus_year` INT NOT NULL,
  `bonus_type` TINYINT NOT NULL DEFAULT 1,
  `bonus_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  `bonus_reason` VARCHAR(200) NULL,
  `pay_status` TINYINT NOT NULL DEFAULT 0,
  `flow_instance_id` BIGINT NULL,
  `apply_status` TINYINT NOT NULL DEFAULT 1,
  `status` TINYINT NOT NULL DEFAULT 1,
  `remark` VARCHAR(500) NULL,
  `create_by` BIGINT NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_by` BIGINT NULL,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_delete` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_company_year` (`company_id`, `bonus_year`, `is_delete`),
  KEY `idx_employee` (`employee_id`, `bonus_year`),
  KEY `idx_flow_instance` (`flow_instance_id`),
  KEY `idx_apply_status` (`company_id`, `apply_status`, `is_delete`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='年终奖/一次性奖金表';
