Remove-Item "D:\Office\Project\Java\gbi_platform\temp\build_all.ps1" -ErrorAction SilentlyContinue
Remove-Item "D:\Office\Project\Java\gbi_platform\temp\build_and_run_all.bat" -ErrorAction SilentlyContinue
Remove-Item "D:\Office\Project\Java\gbi_platform\temp\build_and_run_backend.bat" -ErrorAction SilentlyContinue
Remove-Item "D:\Office\Project\Java\gbi_platform\temp\build_backend.bat" -ErrorAction SilentlyContinue
Remove-Item "D:\Office\Project\Java\gbi_platform\temp\build_backend.ps1" -ErrorAction SilentlyContinue
Remove-Item "D:\Office\Project\Java\gbi_platform\temp\build_frontend.bat" -ErrorAction SilentlyContinue
Remove-Item "D:\Office\Project\Java\gbi_platform\temp\build_frontend.ps1" -ErrorAction SilentlyContinue
Remove-Item "D:\Office\Project\Java\gbi_platform\temp\fix_socialparam.py" -ErrorAction SilentlyContinue
Remove-Item "D:\Office\Project\Java\gbi_platform\temp\rebuild_all.bat" -ErrorAction SilentlyContinue
Remove-Item "D:\Office\Project\Java\gbi_platform\temp\restart_backend.ps1" -ErrorAction SilentlyContinue
Write-Host "临时文件已清理" -ForegroundColor Green
