/**
 * 物业费账单管理接口
 */
import { get, post } from '@/utils/request'
import type { PageResult } from '@/utils/request'

export interface PropertyFeeBillQueryDTO {
  pageNum: number
  pageSize: number
  billMonth?: string
  stallId?: number
  marketId?: number
  payStatus?: number
  calcMode?: number
}

export interface PropertyFeeBillVO {
  id: number
  companyId: number
  stallId: number
  stallNumber?: string
  stallName?: string
  stallMarketName?: string
  categoryName?: string
  merchantId?: number
  billMonth: string
  tenantName?: string
  hasFeeBill?: boolean
  ruleId?: number
  ruleName?: string
  feeItemId?: number
  calcMode?: number
  calcModeText?: string
  periodType?: number
  periodTypeText?: string
  usage?: number
  unitPrice?: number
  periodFactor?: number
  amount: number
  payStatus: number
  payStatusText?: string
  payTime?: string
  planId?: number
  createTime?: string
}

export interface PropertyFeeBillGenerateDTO {
  billMonth: string
  marketId?: number
  stallId?: number
}

export interface PropertyFeeBillPreviewVO {
  stallId?: number
  stallNumber?: string
  stallName?: string
  stallMarketName?: string
  calcMode?: number
  calcModeText?: string
  periodType?: number
  periodTypeText?: string
  usage?: number
  unitPrice?: number
  periodFactor?: number
  amount?: number
  hasExisting?: boolean
}

/** 预览物业费账单金额（不创建账单） */
export function previewPropertyFeeBillApi(data: PropertyFeeBillGenerateDTO): Promise<PropertyFeeBillPreviewVO> {
  return post<PropertyFeeBillPreviewVO>('/property/feeBill/preview', data)
}
/** 物业费账单分页 */
export function getPropertyFeeBillPageApi(params: PropertyFeeBillQueryDTO): Promise<PageResult<PropertyFeeBillVO>> {
  return get<PageResult<PropertyFeeBillVO>>('/property/feeBill/page', params)
}

/** 物业费账单详情 */
export function getPropertyFeeBillDetailApi(id: number): Promise<PropertyFeeBillVO> {
  return get<PropertyFeeBillVO>('/property/feeBill/detail', { id })
}

/** 批量生成物业费账单 */
export function generatePropertyFeeBillApi(data: PropertyFeeBillGenerateDTO): Promise<number> {
  return post<number>('/property/feeBill/generate', data)
}

/** 单条生成物业费账单 */
export function generatePropertyFeeBillSingleApi(data: PropertyFeeBillGenerateDTO): Promise<number> {
  return post<number>('/property/feeBill/generateSingle', data)
}

/* ------------------------------ 自动生成记录 ------------------------------ */

export interface PropertyFeeBillAutoGenerateDTO {
  /** 目标月份 yyyy-MM（可选，不填则默认当月） */
  targetMonth?: string
  /** 市场ID（可选，null=全部市场） */
  marketId?: number
}

/** 自动生成物业费账单（从合约开始到目标月份） */
export function autoGeneratePropertyFeeBillApi(data: PropertyFeeBillAutoGenerateDTO): Promise<number> {
  return post<number>('/property/feeBill/generateAuto', data)
}

/* ------------------------------ 未支付订单聚合 ------------------------------ */

export interface UnpaidBillQueryDTO {
  pageNum: number
  pageSize: number
  billMonth?: string
  stallId?: number
  marketId?: number
}

export interface UnpaidBillVO {
  id: number
  companyId: number
  sourceBillId?: number
  businessType: string
  businessTypeText?: string
  billMonth: string
  stallId: number
  stallNumber?: string
  stallName?: string
  stallMarketName?: string
  categoryName?: string
  amount: number
  payStatus: number
  payStatusText?: string
  payTime?: string
  createTime?: string
  merchantId?: number
  payerName?: string
}

/** 未支付订单分页（聚合物业费 + 水电费） */
export function getUnpaidBillPageApi(params: UnpaidBillQueryDTO): Promise<PageResult<UnpaidBillVO>> {
  return get<PageResult<UnpaidBillVO>>('/property/unpaidBill/page', params)
}
/** 同步已有物业费记录到未支付订单 */
export function syncPropertyFeeBillApi(id: number): Promise<string> {
  return post<string>('/property/feeBill/sync/' + id, null)
}
/** 批量同步物业费记录到未支付订单（finance_fee_pay_bill） */
export function batchSyncPropertyFeeBillApi(ids: number[]): Promise<number> {
  return post<number>('/property/feeBill/batchSync', ids)
}

/** 物业费线下缴费 */
export interface PropertyFeePayDTO {
  billId: number
  payType: number
  requestId: string
  remark?: string
}

export function payPropertyFeeApi(data: PropertyFeePayDTO): Promise<null> {
  return post<null>('/property/feePay/pay', data)
}
/** 物业费账单详情（别名，供缴费页调用） */
export const getFeeBillDetailApi = getPropertyFeeBillDetailApi
/** 统一缴费（物业费/水电费共用入口） */
export interface UnifiedPayDTO {
  billId: number
  billType: string
  payType: number
  requestId: string
  remark?: string
}

export function unifiedPayApi(data: UnifiedPayDTO): Promise<null> {
  return post<null>('/property/unifiedPay/pay', data)
}

/* ------------------------------ 缴费单聚合支付 ------------------------------ */

/** 缴费单明细VO */
export interface PayBillItemVO {
  id: number
  payBillId: number
  billId: number
  bizType: string
  ruleName?: string
  feeItemName?: string
  billMonth: string
  amount: number
  paidAmount: number
  unpaidAmount: number
}

/** 缴费单VO */
export interface PayBillVO {
  id: number
  payBillNo: string
  sourceType?: string
  sourceId?: number
  stallId?: number
  merchantId?: number
  totalAmount: number
  paidAmount: number
  unpaidAmount: number
  payStatus: number
  payStatusText?: string
  payTime?: string
  remark?: string
  createTime?: string
  items?: PayBillItemVO[]
}

/** 创建缴费单入参 */
export interface PayBillCreateDTO {
  bizFeeBillIds: number[]
  remark?: string
}

/** 缴费单缴费入参 */
export interface PayBillPayDTO {
  payBillId: number
  payType: number
  requestId: string
  remark?: string
}

/** 缴费单退费入参 */
export interface PayBillRefundDTO {
  payBillId: number
  refundAmount: number
  remark?: string
}

/** 缴费单分页查询 */
export interface PayBillQueryDTO {
  pageNum: number
  pageSize: number
  payStatus?: number
  stallId?: number
  payBillNo?: string
}

/** 创建缴费单 */
export function createPayBillApi(data: PayBillCreateDTO): Promise<number> {
  return post<number>('/property/payBill/create', data)
}

/** 缴费单聚合缴费 */
export function payPayBillApi(data: PayBillPayDTO): Promise<null> {
  return post<null>('/property/payBill/pay', data)
}

/** 缴费单分页查询 */
export function getPayBillPageApi(params: PayBillQueryDTO): Promise<PageResult<PayBillVO>> {
  return get<PageResult<PayBillVO>>('/property/payBill/page', params)
}

/** 缴费单详情 */
export function getPayBillDetailApi(id: number): Promise<PayBillVO> {
  return get<PayBillVO>('/property/payBill/detail/' + id)
}

/** 作废缴费单 */
export function voidPayBillApi(id: number): Promise<null> {
  return post<null>('/property/payBill/void/' + id, null)
}