package com.gbi.platform.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.io.Serial;
import java.io.Serializable;

/**
 * 物业费自动生成入参
 *
 * @author gbi
 */
@Data
@Schema(description = "物业费自动生成入参")
public class PropertyFeeBillAutoGenerateDTO implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    @Schema(description = "目标月份 yyyy-MM（不填则默认当月）")
    private String targetMonth;

    @Schema(description = "市场ID（不填则全部市场）")
    private Long marketId;
}